import React from "react";

import {Chip, Button} from '@mui/material';
import { VerticalTimeline, VerticalTimelineElement } from 'react-vertical-timeline-component';
import 'react-vertical-timeline-component/style.min.css';
import appTheme from '../theme';

const projects = [
    {
        title: 'OVH provider for External DNS Rancher',
        subtitle: 'GO Library',
        category: 'library',
        subcategory: 'go',
        contribution: true,
        links: [
            {
                url: 'https://github.com/rancher/external-dns/pull/105',
                text: 'View source code',
            },
        ],
        technologies: [
            {
                name: 'GO',
            },
            {
                name: 'Rancher',
            },
        ],
        content:
            'Contributions to a Rancher library which gives the ability to update external DNS with records generated by Rancher.',
        date: '2018-03-08',
    },
    {
        title: 'React Fake Code Typing',
        subtitle: 'React Component',
        category: 'library',
        subcategory: 'react',
        links: [
            {
                url: 'https://stephanemonnot.com/404.html',
                text: 'View demo',
            },
            {
                url: 'https://github.com/stephane-monnot/react-fake-code-typing',
                text: 'View source code',
            },
        ],
        technologies: [
            {
                name: 'ReactJS',
            },
        ],
        content: 'A react component to generate fake code typing.',
        date: '2018-01-24',
    },
    {
        title: 'Leo Pole Consulting SAS',
        subtitle: 'WordPress Project',
        category: 'project',
        subcategory: 'wordpress',
        links: [
            {
                url: 'http://leo-pole.fr/',
                text: 'Visit website',
            },
        ],
        technologies: [
            {
                name: 'PHP',
            },
            {
                name: 'WordPress',
            },
            {
                name: 'Multi-language',
            },
        ],
        content:
            'Showcase website of the Leo Pole Consulting SAS company built with WordPress in French and English.',
        date: '2018-01-10',
    },
    {
        title: 'Resume generator',
        subtitle: 'Laravel Project',
        category: 'project',
        subcategory: 'laravel',
        links: [],
        technologies: [
            {
                name: 'PHP',
            },
            {
                name: 'Laravel',
            },
            {
                name: 'Continuous deployment',
            },
        ],
        content:
            'Website which gives the ability to generate resume from a JSON. A resume is a combination of a PDF resume and a website resume in React.',
        date: 'In progress',
    }
];


const Projects = () => {

    return (
        <VerticalTimeline>
            {projects.map((project, i) => (
                <VerticalTimelineElement
                    style={{
                        borderTop: `3px solid ${appTheme[`${project.subcategory}Color`].border
                            }`,
                    }}
                    className={`ResumeProjectsBlock ${appTheme[`${project.subcategory}Color`].className
                        }`}
                    key={i} // eslint-disable-line react/no-array-index-key
                    icon={appTheme[`${project.subcategory}Color`].icon}
                    iconStyle={appTheme[`${project.subcategory}Color`].style}
                // date={formatProjectDate(project.data)}
                >
                    <div className="ResumeProjectsBlock-technologies">
                        {project.technologies.map((technology, j) => (
                            <Chip key={j} label={technology.name} /> // eslint-disable-line react/no-array-index-key
                        ))}
                    </div>
                    <h3 className="vertical-timeline-element-title">
                        {project.title}
                    </h3>
                    <h4 className="vertical-timeline-element-subtitle">
                        {project.subtitle}
                    </h4>
                    <p>
                        {/* eslint-disable-next-line react/no-danger */}
                        <span>
                        {project.content}
                        </span>
                    </p>
                    <br />
                    <div className="ResumeProjectsBlock-links">
                    </div>
                </VerticalTimelineElement>
            ))}
        </VerticalTimeline>
    )
}

export default Projects;
