import React from "react";

import { makeStyles } from "@mui/styles";
import 'react-vertical-timeline-component/style.min.css';
import WrapperSection from "../../components/section";
import { Container, Typography } from "@mui/material";
import { Box } from "@mui/system";

// const projects = [
//     {
//         title: 'OVH provider for External DNS Rancher',
//         subtitle: 'GO Library',
//         category: 'library',
//         subcategory: 'go',
//         contribution: true,
//         links: [
//             {
//                 url: 'https://github.com/rancher/external-dns/pull/105',
//                 text: 'View source code',
//             },
//         ],
//         technologies: [
//             {
//                 name: 'GO',
//             },
//             {
//                 name: 'Rancher',
//             },
//         ],
//         content:
//             'Contributions to a Rancher library which gives the ability to update external DNS with records generated by Rancher.',
//         date: '2018-03-08',
//     },
//     {
//         title: 'React Fake Code Typing',
//         subtitle: 'React Component',
//         category: 'library',
//         subcategory: 'react',
//         links: [
//             {
//                 url: 'https://stephanemonnot.com/404.html',
//                 text: 'View demo',
//             },
//             {
//                 url: 'https://github.com/stephane-monnot/react-fake-code-typing',
//                 text: 'View source code',
//             },
//         ],
//         technologies: [
//             {
//                 name: 'ReactJS',
//             },
//         ],
//         content: 'A react component to generate fake code typing.',
//         date: '2018-01-24',
//     },
//     {
//         title: 'Leo Pole Consulting SAS',
//         subtitle: 'WordPress Project',
//         category: 'project',
//         subcategory: 'wordpress',
//         links: [
//             {
//                 url: 'http://leo-pole.fr/',
//                 text: 'Visit website',
//             },
//         ],
//         technologies: [
//             {
//                 name: 'PHP',
//             },
//             {
//                 name: 'WordPress',
//             },
//             {
//                 name: 'Multi-language',
//             },
//         ],
//         content:
//             'Showcase website of the Leo Pole Consulting SAS company built with WordPress in French and English.',
//         date: '2018-01-10',
//     },
//     {
//         title: 'Resume generator',
//         subtitle: 'Laravel Project',
//         category: 'project',
//         subcategory: 'laravel',
//         links: [],
//         technologies: [
//             {
//                 name: 'PHP',
//             },
//             {
//                 name: 'Laravel',
//             },
//             {
//                 name: 'Continuous deployment',
//             },
//         ],
//         content:
//             'Website which gives the ability to generate resume from a JSON. A resume is a combination of a PDF resume and a website resume in React.',
//         date: 'In progress',
//     }
// ];


const Projects = () => {
    const useStyles = makeStyles({
        projects: {
            display: 'flex',
            alignItems: 'center',
            gap: 66,
            margin: '0 auto'

        },
        proImg: {
            width: 121,
            height: 121,
            borderRadius: '100%'
        },
    })

    const classes = useStyles();
    return (
        <WrapperSection classVariant={`${classes.sectionAbout} about-section`}>
            <Container>
                <div class="titles" style={{ textAlign: 'center', width: '100%', paddingTop: '5%' }}>
                    <h2 class="title"><div className='inner-txt'> Projects </div></h2>
                    {/* <div class="subtitle"><span> My Story </span></div> */}
                </div>
                <Box className={`project-hldr ${classes.projects}`} borderBottom='1px solid #FE6B8B' paddingY={'30px'}>
                    <img className={`${classes.proImg}`} src={require('../../assets/images/svg/APP/study.svg')} alt="projects" />
                    <div>
                        <Box whiteSpace='nowrap'>
                            <Box display={'inline'}>Date:</Box>
                            <Box>Dec 19 2021</Box>
                        </Box>
                        <Box whiteSpace='nowrap' mt='12px'>
                            <Box display={'inline'}>Category:</Box>
                            <Box>Dec 19 2021</Box>
                        </Box>
                    </div>
                    <div>
                        <Typography variant="h3">IOT</Typography>
                        <Typography textAlign={'justify'}>
                            Duis occaecat irure labore veniam id fugiat consequat tempor amet consectetur cillum voluptate. Sint aliquip non officia veniam excepteur. Do amet et tempor sit enim.
                            Reprehenderit reprehenderit minim velit nulla. Nostrud consequat in mollit quis cupidatat nisi. Velit fugiat nulla anim aliquip dolor laboris non amet ad esse irure consectetur. Ut nisi duis do laboris deserunt exercitation elit
                            est laborum elit dolore adipisicing fugiat. Esse officia deserunt pariatur nulla in duis amet dolore culpa cillum esse magna.
                        </Typography>
                    </div>

                </Box>
            </Container>
        </WrapperSection>
    )
}

export default Projects;
